/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as JoinRouteImport } from './routes/join'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoansIndexRouteImport } from './routes/loans/index'
import { Route as AccountsIndexRouteImport } from './routes/accounts/index'
import { Route as LoansVehicleLoansRouteImport } from './routes/loans/vehicle-loans'
import { Route as LoansStudentLoansRouteImport } from './routes/loans/student-loans'
import { Route as LoansPersonalCreditRouteImport } from './routes/loans/personal-credit'
import { Route as LoansHomeLoansRouteImport } from './routes/loans/home-loans'
import { Route as AccountsYouthRouteImport } from './routes/accounts/youth'
import { Route as AccountsSavingsRouteImport } from './routes/accounts/savings'
import { Route as AccountsCheckingRouteImport } from './routes/accounts/checking'
import { Route as AccountsCertificatesRouteImport } from './routes/accounts/certificates'

const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoansIndexRoute = LoansIndexRouteImport.update({
  id: '/loans/',
  path: '/loans/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsIndexRoute = AccountsIndexRouteImport.update({
  id: '/accounts/',
  path: '/accounts/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoansVehicleLoansRoute = LoansVehicleLoansRouteImport.update({
  id: '/loans/vehicle-loans',
  path: '/loans/vehicle-loans',
  getParentRoute: () => rootRouteImport,
} as any)
const LoansStudentLoansRoute = LoansStudentLoansRouteImport.update({
  id: '/loans/student-loans',
  path: '/loans/student-loans',
  getParentRoute: () => rootRouteImport,
} as any)
const LoansPersonalCreditRoute = LoansPersonalCreditRouteImport.update({
  id: '/loans/personal-credit',
  path: '/loans/personal-credit',
  getParentRoute: () => rootRouteImport,
} as any)
const LoansHomeLoansRoute = LoansHomeLoansRouteImport.update({
  id: '/loans/home-loans',
  path: '/loans/home-loans',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsYouthRoute = AccountsYouthRouteImport.update({
  id: '/accounts/youth',
  path: '/accounts/youth',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsSavingsRoute = AccountsSavingsRouteImport.update({
  id: '/accounts/savings',
  path: '/accounts/savings',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsCheckingRoute = AccountsCheckingRouteImport.update({
  id: '/accounts/checking',
  path: '/accounts/checking',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsCertificatesRoute = AccountsCertificatesRouteImport.update({
  id: '/accounts/certificates',
  path: '/accounts/certificates',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/join': typeof JoinRoute
  '/accounts/certificates': typeof AccountsCertificatesRoute
  '/accounts/checking': typeof AccountsCheckingRoute
  '/accounts/savings': typeof AccountsSavingsRoute
  '/accounts/youth': typeof AccountsYouthRoute
  '/loans/home-loans': typeof LoansHomeLoansRoute
  '/loans/personal-credit': typeof LoansPersonalCreditRoute
  '/loans/student-loans': typeof LoansStudentLoansRoute
  '/loans/vehicle-loans': typeof LoansVehicleLoansRoute
  '/accounts/': typeof AccountsIndexRoute
  '/loans/': typeof LoansIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/join': typeof JoinRoute
  '/accounts/certificates': typeof AccountsCertificatesRoute
  '/accounts/checking': typeof AccountsCheckingRoute
  '/accounts/savings': typeof AccountsSavingsRoute
  '/accounts/youth': typeof AccountsYouthRoute
  '/loans/home-loans': typeof LoansHomeLoansRoute
  '/loans/personal-credit': typeof LoansPersonalCreditRoute
  '/loans/student-loans': typeof LoansStudentLoansRoute
  '/loans/vehicle-loans': typeof LoansVehicleLoansRoute
  '/accounts': typeof AccountsIndexRoute
  '/loans': typeof LoansIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/join': typeof JoinRoute
  '/accounts/certificates': typeof AccountsCertificatesRoute
  '/accounts/checking': typeof AccountsCheckingRoute
  '/accounts/savings': typeof AccountsSavingsRoute
  '/accounts/youth': typeof AccountsYouthRoute
  '/loans/home-loans': typeof LoansHomeLoansRoute
  '/loans/personal-credit': typeof LoansPersonalCreditRoute
  '/loans/student-loans': typeof LoansStudentLoansRoute
  '/loans/vehicle-loans': typeof LoansVehicleLoansRoute
  '/accounts/': typeof AccountsIndexRoute
  '/loans/': typeof LoansIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/join'
    | '/accounts/certificates'
    | '/accounts/checking'
    | '/accounts/savings'
    | '/accounts/youth'
    | '/loans/home-loans'
    | '/loans/personal-credit'
    | '/loans/student-loans'
    | '/loans/vehicle-loans'
    | '/accounts/'
    | '/loans/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/join'
    | '/accounts/certificates'
    | '/accounts/checking'
    | '/accounts/savings'
    | '/accounts/youth'
    | '/loans/home-loans'
    | '/loans/personal-credit'
    | '/loans/student-loans'
    | '/loans/vehicle-loans'
    | '/accounts'
    | '/loans'
  id:
    | '__root__'
    | '/'
    | '/join'
    | '/accounts/certificates'
    | '/accounts/checking'
    | '/accounts/savings'
    | '/accounts/youth'
    | '/loans/home-loans'
    | '/loans/personal-credit'
    | '/loans/student-loans'
    | '/loans/vehicle-loans'
    | '/accounts/'
    | '/loans/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  JoinRoute: typeof JoinRoute
  AccountsCertificatesRoute: typeof AccountsCertificatesRoute
  AccountsCheckingRoute: typeof AccountsCheckingRoute
  AccountsSavingsRoute: typeof AccountsSavingsRoute
  AccountsYouthRoute: typeof AccountsYouthRoute
  LoansHomeLoansRoute: typeof LoansHomeLoansRoute
  LoansPersonalCreditRoute: typeof LoansPersonalCreditRoute
  LoansStudentLoansRoute: typeof LoansStudentLoansRoute
  LoansVehicleLoansRoute: typeof LoansVehicleLoansRoute
  AccountsIndexRoute: typeof AccountsIndexRoute
  LoansIndexRoute: typeof LoansIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loans/': {
      id: '/loans/'
      path: '/loans'
      fullPath: '/loans/'
      preLoaderRoute: typeof LoansIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts/': {
      id: '/accounts/'
      path: '/accounts'
      fullPath: '/accounts/'
      preLoaderRoute: typeof AccountsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loans/vehicle-loans': {
      id: '/loans/vehicle-loans'
      path: '/loans/vehicle-loans'
      fullPath: '/loans/vehicle-loans'
      preLoaderRoute: typeof LoansVehicleLoansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loans/student-loans': {
      id: '/loans/student-loans'
      path: '/loans/student-loans'
      fullPath: '/loans/student-loans'
      preLoaderRoute: typeof LoansStudentLoansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loans/personal-credit': {
      id: '/loans/personal-credit'
      path: '/loans/personal-credit'
      fullPath: '/loans/personal-credit'
      preLoaderRoute: typeof LoansPersonalCreditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loans/home-loans': {
      id: '/loans/home-loans'
      path: '/loans/home-loans'
      fullPath: '/loans/home-loans'
      preLoaderRoute: typeof LoansHomeLoansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts/youth': {
      id: '/accounts/youth'
      path: '/accounts/youth'
      fullPath: '/accounts/youth'
      preLoaderRoute: typeof AccountsYouthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts/savings': {
      id: '/accounts/savings'
      path: '/accounts/savings'
      fullPath: '/accounts/savings'
      preLoaderRoute: typeof AccountsSavingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts/checking': {
      id: '/accounts/checking'
      path: '/accounts/checking'
      fullPath: '/accounts/checking'
      preLoaderRoute: typeof AccountsCheckingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts/certificates': {
      id: '/accounts/certificates'
      path: '/accounts/certificates'
      fullPath: '/accounts/certificates'
      preLoaderRoute: typeof AccountsCertificatesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  JoinRoute: JoinRoute,
  AccountsCertificatesRoute: AccountsCertificatesRoute,
  AccountsCheckingRoute: AccountsCheckingRoute,
  AccountsSavingsRoute: AccountsSavingsRoute,
  AccountsYouthRoute: AccountsYouthRoute,
  LoansHomeLoansRoute: LoansHomeLoansRoute,
  LoansPersonalCreditRoute: LoansPersonalCreditRoute,
  LoansStudentLoansRoute: LoansStudentLoansRoute,
  LoansVehicleLoansRoute: LoansVehicleLoansRoute,
  AccountsIndexRoute: AccountsIndexRoute,
  LoansIndexRoute: LoansIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
