/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LocationsRouteImport } from './routes/locations'
import { Route as JoinRouteImport } from './routes/join'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactUsRouteImport } from './routes/contact-us'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WhoWeAreIndexRouteImport } from './routes/who-we-are/index'
import { Route as ServicesIndexRouteImport } from './routes/services/index'
import { Route as LoansIndexRouteImport } from './routes/loans/index'
import { Route as JoinIndexRouteImport } from './routes/join/index'
import { Route as GuidanceIndexRouteImport } from './routes/guidance/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as BusinessIndexRouteImport } from './routes/business/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AccountsIndexRouteImport } from './routes/accounts/index'
import { Route as WhoWeAreMembershipRouteImport } from './routes/who-we-are/membership'
import { Route as WhoWeAreCommunityRouteImport } from './routes/who-we-are/community'
import { Route as WhoWeAreAboutRouteImport } from './routes/who-we-are/about'
import { Route as ServicesOnlineBankingRouteImport } from './routes/services/online-banking'
import { Route as ServicesMobileBankingRouteImport } from './routes/services/mobile-banking'
import { Route as ServicesMemberServicesRouteImport } from './routes/services/member-services'
import { Route as ServicesInsuranceInvestmentsRouteImport } from './routes/services/insurance-investments'
import { Route as LoansVehicleLoansRouteImport } from './routes/loans/vehicle-loans'
import { Route as LoansStudentLoansRouteImport } from './routes/loans/student-loans'
import { Route as LoansPersonalCreditRouteImport } from './routes/loans/personal-credit'
import { Route as LoansHomeLoansRouteImport } from './routes/loans/home-loans'
import { Route as JoinReviewRouteImport } from './routes/join/review'
import { Route as JoinPersonalRouteImport } from './routes/join/personal'
import { Route as JoinGoalsRouteImport } from './routes/join/goals'
import { Route as JoinConfirmationRouteImport } from './routes/join/confirmation'
import { Route as JoinAccountRouteImport } from './routes/join/account'
import { Route as GuidanceToolsRouteImport } from './routes/guidance/tools'
import { Route as GuidanceRatesRouteImport } from './routes/guidance/rates'
import { Route as GuidanceFinancialEducationRouteImport } from './routes/guidance/financial-education'
import { Route as DashboardTransferRouteImport } from './routes/dashboard/transfer'
import { Route as DashboardStatementsRouteImport } from './routes/dashboard/statements'
import { Route as DashboardProfileRouteImport } from './routes/dashboard/profile'
import { Route as DashboardDepositHistoryRouteImport } from './routes/dashboard/deposit-history'
import { Route as DashboardDepositRouteImport } from './routes/dashboard/deposit'
import { Route as DashboardChecksRouteImport } from './routes/dashboard/checks'
import { Route as DashboardBillsRouteImport } from './routes/dashboard/bills'
import { Route as BusinessServicesRouteImport } from './routes/business/services'
import { Route as BusinessLendingRouteImport } from './routes/business/lending'
import { Route as BusinessAccountsRouteImport } from './routes/business/accounts'
import { Route as AdminDepositsRouteImport } from './routes/admin/deposits'
import { Route as AdminChatRouteImport } from './routes/admin/chat'
import { Route as AccountsYouthRouteImport } from './routes/accounts/youth'
import { Route as AccountsSavingsRouteImport } from './routes/accounts/savings'
import { Route as AccountsCheckingRouteImport } from './routes/accounts/checking'
import { Route as AccountsCertificatesRouteImport } from './routes/accounts/certificates'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsRoute = LocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactUsRoute = ContactUsRouteImport.update({
  id: '/contact-us',
  path: '/contact-us',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WhoWeAreIndexRoute = WhoWeAreIndexRouteImport.update({
  id: '/who-we-are/',
  path: '/who-we-are/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoansIndexRoute = LoansIndexRouteImport.update({
  id: '/loans/',
  path: '/loans/',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinIndexRoute = JoinIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => JoinRoute,
} as any)
const GuidanceIndexRoute = GuidanceIndexRouteImport.update({
  id: '/guidance/',
  path: '/guidance/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const BusinessIndexRoute = BusinessIndexRouteImport.update({
  id: '/business/',
  path: '/business/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AccountsIndexRoute = AccountsIndexRouteImport.update({
  id: '/accounts/',
  path: '/accounts/',
  getParentRoute: () => rootRouteImport,
} as any)
const WhoWeAreMembershipRoute = WhoWeAreMembershipRouteImport.update({
  id: '/who-we-are/membership',
  path: '/who-we-are/membership',
  getParentRoute: () => rootRouteImport,
} as any)
const WhoWeAreCommunityRoute = WhoWeAreCommunityRouteImport.update({
  id: '/who-we-are/community',
  path: '/who-we-are/community',
  getParentRoute: () => rootRouteImport,
} as any)
const WhoWeAreAboutRoute = WhoWeAreAboutRouteImport.update({
  id: '/who-we-are/about',
  path: '/who-we-are/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesOnlineBankingRoute = ServicesOnlineBankingRouteImport.update({
  id: '/services/online-banking',
  path: '/services/online-banking',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesMobileBankingRoute = ServicesMobileBankingRouteImport.update({
  id: '/services/mobile-banking',
  path: '/services/mobile-banking',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesMemberServicesRoute = ServicesMemberServicesRouteImport.update({
  id: '/services/member-services',
  path: '/services/member-services',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesInsuranceInvestmentsRoute =
  ServicesInsuranceInvestmentsRouteImport.update({
    id: '/services/insurance-investments',
    path: '/services/insurance-investments',
    getParentRoute: () => rootRouteImport,
  } as any)
const LoansVehicleLoansRoute = LoansVehicleLoansRouteImport.update({
  id: '/loans/vehicle-loans',
  path: '/loans/vehicle-loans',
  getParentRoute: () => rootRouteImport,
} as any)
const LoansStudentLoansRoute = LoansStudentLoansRouteImport.update({
  id: '/loans/student-loans',
  path: '/loans/student-loans',
  getParentRoute: () => rootRouteImport,
} as any)
const LoansPersonalCreditRoute = LoansPersonalCreditRouteImport.update({
  id: '/loans/personal-credit',
  path: '/loans/personal-credit',
  getParentRoute: () => rootRouteImport,
} as any)
const LoansHomeLoansRoute = LoansHomeLoansRouteImport.update({
  id: '/loans/home-loans',
  path: '/loans/home-loans',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinReviewRoute = JoinReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => JoinRoute,
} as any)
const JoinPersonalRoute = JoinPersonalRouteImport.update({
  id: '/personal',
  path: '/personal',
  getParentRoute: () => JoinRoute,
} as any)
const JoinGoalsRoute = JoinGoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => JoinRoute,
} as any)
const JoinConfirmationRoute = JoinConfirmationRouteImport.update({
  id: '/confirmation',
  path: '/confirmation',
  getParentRoute: () => JoinRoute,
} as any)
const JoinAccountRoute = JoinAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => JoinRoute,
} as any)
const GuidanceToolsRoute = GuidanceToolsRouteImport.update({
  id: '/guidance/tools',
  path: '/guidance/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidanceRatesRoute = GuidanceRatesRouteImport.update({
  id: '/guidance/rates',
  path: '/guidance/rates',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidanceFinancialEducationRoute =
  GuidanceFinancialEducationRouteImport.update({
    id: '/guidance/financial-education',
    path: '/guidance/financial-education',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardTransferRoute = DashboardTransferRouteImport.update({
  id: '/transfer',
  path: '/transfer',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardStatementsRoute = DashboardStatementsRouteImport.update({
  id: '/statements',
  path: '/statements',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDepositHistoryRoute = DashboardDepositHistoryRouteImport.update({
  id: '/deposit-history',
  path: '/deposit-history',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDepositRoute = DashboardDepositRouteImport.update({
  id: '/deposit',
  path: '/deposit',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardChecksRoute = DashboardChecksRouteImport.update({
  id: '/checks',
  path: '/checks',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBillsRoute = DashboardBillsRouteImport.update({
  id: '/bills',
  path: '/bills',
  getParentRoute: () => DashboardRoute,
} as any)
const BusinessServicesRoute = BusinessServicesRouteImport.update({
  id: '/business/services',
  path: '/business/services',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessLendingRoute = BusinessLendingRouteImport.update({
  id: '/business/lending',
  path: '/business/lending',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessAccountsRoute = BusinessAccountsRouteImport.update({
  id: '/business/accounts',
  path: '/business/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDepositsRoute = AdminDepositsRouteImport.update({
  id: '/deposits',
  path: '/deposits',
  getParentRoute: () => AdminRoute,
} as any)
const AdminChatRoute = AdminChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AdminRoute,
} as any)
const AccountsYouthRoute = AccountsYouthRouteImport.update({
  id: '/accounts/youth',
  path: '/accounts/youth',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsSavingsRoute = AccountsSavingsRouteImport.update({
  id: '/accounts/savings',
  path: '/accounts/savings',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsCheckingRoute = AccountsCheckingRouteImport.update({
  id: '/accounts/checking',
  path: '/accounts/checking',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsCertificatesRoute = AccountsCertificatesRouteImport.update({
  id: '/accounts/certificates',
  path: '/accounts/certificates',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact-us': typeof ContactUsRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/join': typeof JoinRouteWithChildren
  '/locations': typeof LocationsRoute
  '/login': typeof LoginRoute
  '/accounts/certificates': typeof AccountsCertificatesRoute
  '/accounts/checking': typeof AccountsCheckingRoute
  '/accounts/savings': typeof AccountsSavingsRoute
  '/accounts/youth': typeof AccountsYouthRoute
  '/admin/chat': typeof AdminChatRoute
  '/admin/deposits': typeof AdminDepositsRoute
  '/business/accounts': typeof BusinessAccountsRoute
  '/business/lending': typeof BusinessLendingRoute
  '/business/services': typeof BusinessServicesRoute
  '/dashboard/bills': typeof DashboardBillsRoute
  '/dashboard/checks': typeof DashboardChecksRoute
  '/dashboard/deposit': typeof DashboardDepositRoute
  '/dashboard/deposit-history': typeof DashboardDepositHistoryRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/statements': typeof DashboardStatementsRoute
  '/dashboard/transfer': typeof DashboardTransferRoute
  '/guidance/financial-education': typeof GuidanceFinancialEducationRoute
  '/guidance/rates': typeof GuidanceRatesRoute
  '/guidance/tools': typeof GuidanceToolsRoute
  '/join/account': typeof JoinAccountRoute
  '/join/confirmation': typeof JoinConfirmationRoute
  '/join/goals': typeof JoinGoalsRoute
  '/join/personal': typeof JoinPersonalRoute
  '/join/review': typeof JoinReviewRoute
  '/loans/home-loans': typeof LoansHomeLoansRoute
  '/loans/personal-credit': typeof LoansPersonalCreditRoute
  '/loans/student-loans': typeof LoansStudentLoansRoute
  '/loans/vehicle-loans': typeof LoansVehicleLoansRoute
  '/services/insurance-investments': typeof ServicesInsuranceInvestmentsRoute
  '/services/member-services': typeof ServicesMemberServicesRoute
  '/services/mobile-banking': typeof ServicesMobileBankingRoute
  '/services/online-banking': typeof ServicesOnlineBankingRoute
  '/who-we-are/about': typeof WhoWeAreAboutRoute
  '/who-we-are/community': typeof WhoWeAreCommunityRoute
  '/who-we-are/membership': typeof WhoWeAreMembershipRoute
  '/accounts/': typeof AccountsIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/business/': typeof BusinessIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/guidance/': typeof GuidanceIndexRoute
  '/join/': typeof JoinIndexRoute
  '/loans/': typeof LoansIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/who-we-are/': typeof WhoWeAreIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact-us': typeof ContactUsRoute
  '/locations': typeof LocationsRoute
  '/login': typeof LoginRoute
  '/accounts/certificates': typeof AccountsCertificatesRoute
  '/accounts/checking': typeof AccountsCheckingRoute
  '/accounts/savings': typeof AccountsSavingsRoute
  '/accounts/youth': typeof AccountsYouthRoute
  '/admin/chat': typeof AdminChatRoute
  '/admin/deposits': typeof AdminDepositsRoute
  '/business/accounts': typeof BusinessAccountsRoute
  '/business/lending': typeof BusinessLendingRoute
  '/business/services': typeof BusinessServicesRoute
  '/dashboard/bills': typeof DashboardBillsRoute
  '/dashboard/checks': typeof DashboardChecksRoute
  '/dashboard/deposit': typeof DashboardDepositRoute
  '/dashboard/deposit-history': typeof DashboardDepositHistoryRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/statements': typeof DashboardStatementsRoute
  '/dashboard/transfer': typeof DashboardTransferRoute
  '/guidance/financial-education': typeof GuidanceFinancialEducationRoute
  '/guidance/rates': typeof GuidanceRatesRoute
  '/guidance/tools': typeof GuidanceToolsRoute
  '/join/account': typeof JoinAccountRoute
  '/join/confirmation': typeof JoinConfirmationRoute
  '/join/goals': typeof JoinGoalsRoute
  '/join/personal': typeof JoinPersonalRoute
  '/join/review': typeof JoinReviewRoute
  '/loans/home-loans': typeof LoansHomeLoansRoute
  '/loans/personal-credit': typeof LoansPersonalCreditRoute
  '/loans/student-loans': typeof LoansStudentLoansRoute
  '/loans/vehicle-loans': typeof LoansVehicleLoansRoute
  '/services/insurance-investments': typeof ServicesInsuranceInvestmentsRoute
  '/services/member-services': typeof ServicesMemberServicesRoute
  '/services/mobile-banking': typeof ServicesMobileBankingRoute
  '/services/online-banking': typeof ServicesOnlineBankingRoute
  '/who-we-are/about': typeof WhoWeAreAboutRoute
  '/who-we-are/community': typeof WhoWeAreCommunityRoute
  '/who-we-are/membership': typeof WhoWeAreMembershipRoute
  '/accounts': typeof AccountsIndexRoute
  '/admin': typeof AdminIndexRoute
  '/business': typeof BusinessIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/guidance': typeof GuidanceIndexRoute
  '/join': typeof JoinIndexRoute
  '/loans': typeof LoansIndexRoute
  '/services': typeof ServicesIndexRoute
  '/who-we-are': typeof WhoWeAreIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact-us': typeof ContactUsRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/join': typeof JoinRouteWithChildren
  '/locations': typeof LocationsRoute
  '/login': typeof LoginRoute
  '/accounts/certificates': typeof AccountsCertificatesRoute
  '/accounts/checking': typeof AccountsCheckingRoute
  '/accounts/savings': typeof AccountsSavingsRoute
  '/accounts/youth': typeof AccountsYouthRoute
  '/admin/chat': typeof AdminChatRoute
  '/admin/deposits': typeof AdminDepositsRoute
  '/business/accounts': typeof BusinessAccountsRoute
  '/business/lending': typeof BusinessLendingRoute
  '/business/services': typeof BusinessServicesRoute
  '/dashboard/bills': typeof DashboardBillsRoute
  '/dashboard/checks': typeof DashboardChecksRoute
  '/dashboard/deposit': typeof DashboardDepositRoute
  '/dashboard/deposit-history': typeof DashboardDepositHistoryRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/statements': typeof DashboardStatementsRoute
  '/dashboard/transfer': typeof DashboardTransferRoute
  '/guidance/financial-education': typeof GuidanceFinancialEducationRoute
  '/guidance/rates': typeof GuidanceRatesRoute
  '/guidance/tools': typeof GuidanceToolsRoute
  '/join/account': typeof JoinAccountRoute
  '/join/confirmation': typeof JoinConfirmationRoute
  '/join/goals': typeof JoinGoalsRoute
  '/join/personal': typeof JoinPersonalRoute
  '/join/review': typeof JoinReviewRoute
  '/loans/home-loans': typeof LoansHomeLoansRoute
  '/loans/personal-credit': typeof LoansPersonalCreditRoute
  '/loans/student-loans': typeof LoansStudentLoansRoute
  '/loans/vehicle-loans': typeof LoansVehicleLoansRoute
  '/services/insurance-investments': typeof ServicesInsuranceInvestmentsRoute
  '/services/member-services': typeof ServicesMemberServicesRoute
  '/services/mobile-banking': typeof ServicesMobileBankingRoute
  '/services/online-banking': typeof ServicesOnlineBankingRoute
  '/who-we-are/about': typeof WhoWeAreAboutRoute
  '/who-we-are/community': typeof WhoWeAreCommunityRoute
  '/who-we-are/membership': typeof WhoWeAreMembershipRoute
  '/accounts/': typeof AccountsIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/business/': typeof BusinessIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/guidance/': typeof GuidanceIndexRoute
  '/join/': typeof JoinIndexRoute
  '/loans/': typeof LoansIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/who-we-are/': typeof WhoWeAreIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/contact-us'
    | '/dashboard'
    | '/join'
    | '/locations'
    | '/login'
    | '/accounts/certificates'
    | '/accounts/checking'
    | '/accounts/savings'
    | '/accounts/youth'
    | '/admin/chat'
    | '/admin/deposits'
    | '/business/accounts'
    | '/business/lending'
    | '/business/services'
    | '/dashboard/bills'
    | '/dashboard/checks'
    | '/dashboard/deposit'
    | '/dashboard/deposit-history'
    | '/dashboard/profile'
    | '/dashboard/statements'
    | '/dashboard/transfer'
    | '/guidance/financial-education'
    | '/guidance/rates'
    | '/guidance/tools'
    | '/join/account'
    | '/join/confirmation'
    | '/join/goals'
    | '/join/personal'
    | '/join/review'
    | '/loans/home-loans'
    | '/loans/personal-credit'
    | '/loans/student-loans'
    | '/loans/vehicle-loans'
    | '/services/insurance-investments'
    | '/services/member-services'
    | '/services/mobile-banking'
    | '/services/online-banking'
    | '/who-we-are/about'
    | '/who-we-are/community'
    | '/who-we-are/membership'
    | '/accounts/'
    | '/admin/'
    | '/business/'
    | '/dashboard/'
    | '/guidance/'
    | '/join/'
    | '/loans/'
    | '/services/'
    | '/who-we-are/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact-us'
    | '/locations'
    | '/login'
    | '/accounts/certificates'
    | '/accounts/checking'
    | '/accounts/savings'
    | '/accounts/youth'
    | '/admin/chat'
    | '/admin/deposits'
    | '/business/accounts'
    | '/business/lending'
    | '/business/services'
    | '/dashboard/bills'
    | '/dashboard/checks'
    | '/dashboard/deposit'
    | '/dashboard/deposit-history'
    | '/dashboard/profile'
    | '/dashboard/statements'
    | '/dashboard/transfer'
    | '/guidance/financial-education'
    | '/guidance/rates'
    | '/guidance/tools'
    | '/join/account'
    | '/join/confirmation'
    | '/join/goals'
    | '/join/personal'
    | '/join/review'
    | '/loans/home-loans'
    | '/loans/personal-credit'
    | '/loans/student-loans'
    | '/loans/vehicle-loans'
    | '/services/insurance-investments'
    | '/services/member-services'
    | '/services/mobile-banking'
    | '/services/online-banking'
    | '/who-we-are/about'
    | '/who-we-are/community'
    | '/who-we-are/membership'
    | '/accounts'
    | '/admin'
    | '/business'
    | '/dashboard'
    | '/guidance'
    | '/join'
    | '/loans'
    | '/services'
    | '/who-we-are'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/contact-us'
    | '/dashboard'
    | '/join'
    | '/locations'
    | '/login'
    | '/accounts/certificates'
    | '/accounts/checking'
    | '/accounts/savings'
    | '/accounts/youth'
    | '/admin/chat'
    | '/admin/deposits'
    | '/business/accounts'
    | '/business/lending'
    | '/business/services'
    | '/dashboard/bills'
    | '/dashboard/checks'
    | '/dashboard/deposit'
    | '/dashboard/deposit-history'
    | '/dashboard/profile'
    | '/dashboard/statements'
    | '/dashboard/transfer'
    | '/guidance/financial-education'
    | '/guidance/rates'
    | '/guidance/tools'
    | '/join/account'
    | '/join/confirmation'
    | '/join/goals'
    | '/join/personal'
    | '/join/review'
    | '/loans/home-loans'
    | '/loans/personal-credit'
    | '/loans/student-loans'
    | '/loans/vehicle-loans'
    | '/services/insurance-investments'
    | '/services/member-services'
    | '/services/mobile-banking'
    | '/services/online-banking'
    | '/who-we-are/about'
    | '/who-we-are/community'
    | '/who-we-are/membership'
    | '/accounts/'
    | '/admin/'
    | '/business/'
    | '/dashboard/'
    | '/guidance/'
    | '/join/'
    | '/loans/'
    | '/services/'
    | '/who-we-are/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ContactUsRoute: typeof ContactUsRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  JoinRoute: typeof JoinRouteWithChildren
  LocationsRoute: typeof LocationsRoute
  LoginRoute: typeof LoginRoute
  AccountsCertificatesRoute: typeof AccountsCertificatesRoute
  AccountsCheckingRoute: typeof AccountsCheckingRoute
  AccountsSavingsRoute: typeof AccountsSavingsRoute
  AccountsYouthRoute: typeof AccountsYouthRoute
  BusinessAccountsRoute: typeof BusinessAccountsRoute
  BusinessLendingRoute: typeof BusinessLendingRoute
  BusinessServicesRoute: typeof BusinessServicesRoute
  GuidanceFinancialEducationRoute: typeof GuidanceFinancialEducationRoute
  GuidanceRatesRoute: typeof GuidanceRatesRoute
  GuidanceToolsRoute: typeof GuidanceToolsRoute
  LoansHomeLoansRoute: typeof LoansHomeLoansRoute
  LoansPersonalCreditRoute: typeof LoansPersonalCreditRoute
  LoansStudentLoansRoute: typeof LoansStudentLoansRoute
  LoansVehicleLoansRoute: typeof LoansVehicleLoansRoute
  ServicesInsuranceInvestmentsRoute: typeof ServicesInsuranceInvestmentsRoute
  ServicesMemberServicesRoute: typeof ServicesMemberServicesRoute
  ServicesMobileBankingRoute: typeof ServicesMobileBankingRoute
  ServicesOnlineBankingRoute: typeof ServicesOnlineBankingRoute
  WhoWeAreAboutRoute: typeof WhoWeAreAboutRoute
  WhoWeAreCommunityRoute: typeof WhoWeAreCommunityRoute
  WhoWeAreMembershipRoute: typeof WhoWeAreMembershipRoute
  AccountsIndexRoute: typeof AccountsIndexRoute
  BusinessIndexRoute: typeof BusinessIndexRoute
  GuidanceIndexRoute: typeof GuidanceIndexRoute
  LoansIndexRoute: typeof LoansIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
  WhoWeAreIndexRoute: typeof WhoWeAreIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations': {
      id: '/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof LocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact-us': {
      id: '/contact-us'
      path: '/contact-us'
      fullPath: '/contact-us'
      preLoaderRoute: typeof ContactUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/who-we-are/': {
      id: '/who-we-are/'
      path: '/who-we-are'
      fullPath: '/who-we-are/'
      preLoaderRoute: typeof WhoWeAreIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loans/': {
      id: '/loans/'
      path: '/loans'
      fullPath: '/loans/'
      preLoaderRoute: typeof LoansIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/': {
      id: '/join/'
      path: '/'
      fullPath: '/join/'
      preLoaderRoute: typeof JoinIndexRouteImport
      parentRoute: typeof JoinRoute
    }
    '/guidance/': {
      id: '/guidance/'
      path: '/guidance'
      fullPath: '/guidance/'
      preLoaderRoute: typeof GuidanceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/business/': {
      id: '/business/'
      path: '/business'
      fullPath: '/business/'
      preLoaderRoute: typeof BusinessIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/accounts/': {
      id: '/accounts/'
      path: '/accounts'
      fullPath: '/accounts/'
      preLoaderRoute: typeof AccountsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/who-we-are/membership': {
      id: '/who-we-are/membership'
      path: '/who-we-are/membership'
      fullPath: '/who-we-are/membership'
      preLoaderRoute: typeof WhoWeAreMembershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/who-we-are/community': {
      id: '/who-we-are/community'
      path: '/who-we-are/community'
      fullPath: '/who-we-are/community'
      preLoaderRoute: typeof WhoWeAreCommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/who-we-are/about': {
      id: '/who-we-are/about'
      path: '/who-we-are/about'
      fullPath: '/who-we-are/about'
      preLoaderRoute: typeof WhoWeAreAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/online-banking': {
      id: '/services/online-banking'
      path: '/services/online-banking'
      fullPath: '/services/online-banking'
      preLoaderRoute: typeof ServicesOnlineBankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/mobile-banking': {
      id: '/services/mobile-banking'
      path: '/services/mobile-banking'
      fullPath: '/services/mobile-banking'
      preLoaderRoute: typeof ServicesMobileBankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/member-services': {
      id: '/services/member-services'
      path: '/services/member-services'
      fullPath: '/services/member-services'
      preLoaderRoute: typeof ServicesMemberServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/insurance-investments': {
      id: '/services/insurance-investments'
      path: '/services/insurance-investments'
      fullPath: '/services/insurance-investments'
      preLoaderRoute: typeof ServicesInsuranceInvestmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loans/vehicle-loans': {
      id: '/loans/vehicle-loans'
      path: '/loans/vehicle-loans'
      fullPath: '/loans/vehicle-loans'
      preLoaderRoute: typeof LoansVehicleLoansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loans/student-loans': {
      id: '/loans/student-loans'
      path: '/loans/student-loans'
      fullPath: '/loans/student-loans'
      preLoaderRoute: typeof LoansStudentLoansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loans/personal-credit': {
      id: '/loans/personal-credit'
      path: '/loans/personal-credit'
      fullPath: '/loans/personal-credit'
      preLoaderRoute: typeof LoansPersonalCreditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loans/home-loans': {
      id: '/loans/home-loans'
      path: '/loans/home-loans'
      fullPath: '/loans/home-loans'
      preLoaderRoute: typeof LoansHomeLoansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/review': {
      id: '/join/review'
      path: '/review'
      fullPath: '/join/review'
      preLoaderRoute: typeof JoinReviewRouteImport
      parentRoute: typeof JoinRoute
    }
    '/join/personal': {
      id: '/join/personal'
      path: '/personal'
      fullPath: '/join/personal'
      preLoaderRoute: typeof JoinPersonalRouteImport
      parentRoute: typeof JoinRoute
    }
    '/join/goals': {
      id: '/join/goals'
      path: '/goals'
      fullPath: '/join/goals'
      preLoaderRoute: typeof JoinGoalsRouteImport
      parentRoute: typeof JoinRoute
    }
    '/join/confirmation': {
      id: '/join/confirmation'
      path: '/confirmation'
      fullPath: '/join/confirmation'
      preLoaderRoute: typeof JoinConfirmationRouteImport
      parentRoute: typeof JoinRoute
    }
    '/join/account': {
      id: '/join/account'
      path: '/account'
      fullPath: '/join/account'
      preLoaderRoute: typeof JoinAccountRouteImport
      parentRoute: typeof JoinRoute
    }
    '/guidance/tools': {
      id: '/guidance/tools'
      path: '/guidance/tools'
      fullPath: '/guidance/tools'
      preLoaderRoute: typeof GuidanceToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guidance/rates': {
      id: '/guidance/rates'
      path: '/guidance/rates'
      fullPath: '/guidance/rates'
      preLoaderRoute: typeof GuidanceRatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guidance/financial-education': {
      id: '/guidance/financial-education'
      path: '/guidance/financial-education'
      fullPath: '/guidance/financial-education'
      preLoaderRoute: typeof GuidanceFinancialEducationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/transfer': {
      id: '/dashboard/transfer'
      path: '/transfer'
      fullPath: '/dashboard/transfer'
      preLoaderRoute: typeof DashboardTransferRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/statements': {
      id: '/dashboard/statements'
      path: '/statements'
      fullPath: '/dashboard/statements'
      preLoaderRoute: typeof DashboardStatementsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/deposit-history': {
      id: '/dashboard/deposit-history'
      path: '/deposit-history'
      fullPath: '/dashboard/deposit-history'
      preLoaderRoute: typeof DashboardDepositHistoryRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/deposit': {
      id: '/dashboard/deposit'
      path: '/deposit'
      fullPath: '/dashboard/deposit'
      preLoaderRoute: typeof DashboardDepositRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/checks': {
      id: '/dashboard/checks'
      path: '/checks'
      fullPath: '/dashboard/checks'
      preLoaderRoute: typeof DashboardChecksRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/bills': {
      id: '/dashboard/bills'
      path: '/bills'
      fullPath: '/dashboard/bills'
      preLoaderRoute: typeof DashboardBillsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/business/services': {
      id: '/business/services'
      path: '/business/services'
      fullPath: '/business/services'
      preLoaderRoute: typeof BusinessServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/lending': {
      id: '/business/lending'
      path: '/business/lending'
      fullPath: '/business/lending'
      preLoaderRoute: typeof BusinessLendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/accounts': {
      id: '/business/accounts'
      path: '/business/accounts'
      fullPath: '/business/accounts'
      preLoaderRoute: typeof BusinessAccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/deposits': {
      id: '/admin/deposits'
      path: '/deposits'
      fullPath: '/admin/deposits'
      preLoaderRoute: typeof AdminDepositsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/chat': {
      id: '/admin/chat'
      path: '/chat'
      fullPath: '/admin/chat'
      preLoaderRoute: typeof AdminChatRouteImport
      parentRoute: typeof AdminRoute
    }
    '/accounts/youth': {
      id: '/accounts/youth'
      path: '/accounts/youth'
      fullPath: '/accounts/youth'
      preLoaderRoute: typeof AccountsYouthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts/savings': {
      id: '/accounts/savings'
      path: '/accounts/savings'
      fullPath: '/accounts/savings'
      preLoaderRoute: typeof AccountsSavingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts/checking': {
      id: '/accounts/checking'
      path: '/accounts/checking'
      fullPath: '/accounts/checking'
      preLoaderRoute: typeof AccountsCheckingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts/certificates': {
      id: '/accounts/certificates'
      path: '/accounts/certificates'
      fullPath: '/accounts/certificates'
      preLoaderRoute: typeof AccountsCertificatesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminChatRoute: typeof AdminChatRoute
  AdminDepositsRoute: typeof AdminDepositsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminChatRoute: AdminChatRoute,
  AdminDepositsRoute: AdminDepositsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DashboardRouteChildren {
  DashboardBillsRoute: typeof DashboardBillsRoute
  DashboardChecksRoute: typeof DashboardChecksRoute
  DashboardDepositRoute: typeof DashboardDepositRoute
  DashboardDepositHistoryRoute: typeof DashboardDepositHistoryRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardStatementsRoute: typeof DashboardStatementsRoute
  DashboardTransferRoute: typeof DashboardTransferRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardBillsRoute: DashboardBillsRoute,
  DashboardChecksRoute: DashboardChecksRoute,
  DashboardDepositRoute: DashboardDepositRoute,
  DashboardDepositHistoryRoute: DashboardDepositHistoryRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardStatementsRoute: DashboardStatementsRoute,
  DashboardTransferRoute: DashboardTransferRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface JoinRouteChildren {
  JoinAccountRoute: typeof JoinAccountRoute
  JoinConfirmationRoute: typeof JoinConfirmationRoute
  JoinGoalsRoute: typeof JoinGoalsRoute
  JoinPersonalRoute: typeof JoinPersonalRoute
  JoinReviewRoute: typeof JoinReviewRoute
  JoinIndexRoute: typeof JoinIndexRoute
}

const JoinRouteChildren: JoinRouteChildren = {
  JoinAccountRoute: JoinAccountRoute,
  JoinConfirmationRoute: JoinConfirmationRoute,
  JoinGoalsRoute: JoinGoalsRoute,
  JoinPersonalRoute: JoinPersonalRoute,
  JoinReviewRoute: JoinReviewRoute,
  JoinIndexRoute: JoinIndexRoute,
}

const JoinRouteWithChildren = JoinRoute._addFileChildren(JoinRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ContactUsRoute: ContactUsRoute,
  DashboardRoute: DashboardRouteWithChildren,
  JoinRoute: JoinRouteWithChildren,
  LocationsRoute: LocationsRoute,
  LoginRoute: LoginRoute,
  AccountsCertificatesRoute: AccountsCertificatesRoute,
  AccountsCheckingRoute: AccountsCheckingRoute,
  AccountsSavingsRoute: AccountsSavingsRoute,
  AccountsYouthRoute: AccountsYouthRoute,
  BusinessAccountsRoute: BusinessAccountsRoute,
  BusinessLendingRoute: BusinessLendingRoute,
  BusinessServicesRoute: BusinessServicesRoute,
  GuidanceFinancialEducationRoute: GuidanceFinancialEducationRoute,
  GuidanceRatesRoute: GuidanceRatesRoute,
  GuidanceToolsRoute: GuidanceToolsRoute,
  LoansHomeLoansRoute: LoansHomeLoansRoute,
  LoansPersonalCreditRoute: LoansPersonalCreditRoute,
  LoansStudentLoansRoute: LoansStudentLoansRoute,
  LoansVehicleLoansRoute: LoansVehicleLoansRoute,
  ServicesInsuranceInvestmentsRoute: ServicesInsuranceInvestmentsRoute,
  ServicesMemberServicesRoute: ServicesMemberServicesRoute,
  ServicesMobileBankingRoute: ServicesMobileBankingRoute,
  ServicesOnlineBankingRoute: ServicesOnlineBankingRoute,
  WhoWeAreAboutRoute: WhoWeAreAboutRoute,
  WhoWeAreCommunityRoute: WhoWeAreCommunityRoute,
  WhoWeAreMembershipRoute: WhoWeAreMembershipRoute,
  AccountsIndexRoute: AccountsIndexRoute,
  BusinessIndexRoute: BusinessIndexRoute,
  GuidanceIndexRoute: GuidanceIndexRoute,
  LoansIndexRoute: LoansIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
  WhoWeAreIndexRoute: WhoWeAreIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
